# Generated by Django 5.2.7 on 2025-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
